[build]
  publish = "dist"
  command = "npm ci && npm run build"

# Site ID for existing taxiumut.ch domain
[build.environment]
  NETLIFY_SITE_ID = "polite-praline-4c4b02"
  NODE_VERSION = "18"

[context.production]
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301