[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[context.production]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[context.production.environment]
  NETLIFY_EMAILS = "adem.polat03@hotmail.com,tuncaycicek@outlook.com"