[build]
  publish = "dist"
  command = "npm ci && npm run build"

# Site ID for existing taxiumut.ch domain
[build.environment]
  NETLIFY_SITE_ID = "polite-praline-4c4b02"
  NODE_VERSION = "18"
  NETLIFY_EMAILS = "adem.polat03@hotmail.com,tuncaycicek@outlook.com"

[context.production]
  command = "npm ci && npm run build"
  publish = "dist"

# Form handling settings
[[plugins]]
  package = "@netlify/plugin-functions"

# Email notifications for form submissions
[build.environment]
  FORM_EMAIL_TO = "adem.polat03@hotmail.com"
  FORM_EMAIL_FROM = "noreply@umuttaxi.ch"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301