[build]
  publish = "dist"
  command = "npm ci && npm run build"

# Site ID for existing taxiumut.ch domain
[build.environment]
  NETLIFY_SITE_ID = "polite-praline-4c4b02"
  NODE_VERSION = "18"

# Environment variables for production
[context.production.environment]
  SENDGRID_API_KEY = "your_sendgrid_api_key_here"
  SENDGRID_FROM_EMAIL = "noreply@umuttaxi.ch"

[context.production]
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301