[build]
  publish = "dist"
  command = "npm run build"

# Site ID for existing taxiumut.ch domain
[build.environment]
  NETLIFY_SITE_ID = "polite-praline-4c4b02"
  NODE_VERSION = "18"
  NETLIFY_EMAILS = "adem.polat03@hotmail.com,tuncaycicek@outlook.com"

[context.production]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301